# Principal Component Analysis

In [2]:
# Create a signal with only 2 useful dimensions
x1 = np.random.normal(size = 100)

In [3]:
x1

array([-0.44243135,  2.44576196, -0.17134737, -0.09495289,  0.40515432,
       -0.22124016,  1.12421808,  1.74254823, -0.07586337,  0.30467561,
       -0.3506489 , -1.29424521, -0.8330825 , -0.39033665,  0.59802897,
       -0.58795786,  0.25023969,  0.45807   ,  1.56438826, -0.72657743,
       -0.28181901, -0.30385731, -1.11385529,  1.09310839, -0.55687216,
       -0.24162962,  0.15850917, -1.66230322,  1.05683893,  0.1757182 ,
        1.63965696,  0.50949443, -0.25960078,  0.85767847, -0.07976174,
       -0.37402069,  0.44938635,  1.44322623,  0.71637108,  0.40785329,
        0.52699044,  1.36246286, -0.25677723,  2.23326332,  0.33656438,
        0.37195839,  1.07083467, -0.15420034, -0.04828721,  1.02851569,
        0.6155653 , -0.8309645 ,  1.04535023,  1.64103658, -0.72232327,
       -0.54616588, -1.01731429,  0.15724565, -0.66952468,  0.5714147 ,
       -0.59150065,  0.15697545,  0.56337406, -1.1693574 , -1.30179273,
        0.05582295,  1.56085175,  2.35119967, -0.57073219, -0.25

In [4]:
x2 = np.random.normal(size= 100)
x3 = x1 + x2

In [5]:
np.c_??


In [6]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]



array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [8]:
X = np.c_[x1,x2,x3]

In [13]:
from sklearn import decomposition

In [14]:
pca = decomposition.PCA()
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [15]:
print (pca.explained_variance_)

[  3.21435140e+00   1.09042899e+00   1.56541943e-32]


In [16]:
# As we can see, only the 2 first components are useful
pca.n_components= 2

In [17]:
X_reduced = pca.fit_transform(X)

In [19]:
X_reduced.head[:4]

AttributeError: 'numpy.ndarray' object has no attribute 'head'

## Generate sample data

In [21]:
time = np.linspace(0, 10, 2000)
s1 = np.sin(2 * time) # signal 1 : sinusoidal signal
s2 = np.sign(np.sin(3 * time)) # signal 2 : square signal
S = np.c_[s1, s2]


In [27]:
S += 0.2 * np.random.normal(size = S.shape) # add noise
S /= S.std(axis=0) # Standardize data

In [31]:
# Mix data
A = np.array([[1, 1], [0.5, 2]]) # mixing matrix
X = np.dot(S, A.T) # generate observations

### Compute ICA

In [35]:
ica = decomposition.FastICA()
S_ = ica.fit_transform(X) # get the estimated sources
A_ = ica.mixing_.T
np.allclose(X, np.dot(S_,A_) + ica.mean_)

True

/Users/bartev/.virtualenvs/skl/lib/python2.7/site-packages/scipy/linalg/basic.py:884: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)
