# Screenshots

http://matplotlib.org/users/screenshots.html

## Simple plot

In [147]:
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = np.sin(2 * np.pi * t)
plt.plot(t, s)

plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(True)
plt.savefig("test.png")
plt.show()

## Subplot demo

In [148]:
"""
Simple demo with multiple subplots.
"""
import numpy as np
import matplotlib.pyplot as plt


x1 = np.linspace(0.0, 5.0)
x2 = np.linspace(0.0, 2.0)

y1 = np.cos(2 * np.pi * x1) * np.exp(-x1)
y2 = np.cos(2 * np.pi * x2)

plt.subplot(2, 1, 1)
plt.plot(x1, y1, 'yo-')
plt.title('A tale of 2 subplots')
plt.ylabel('Damped oscillation')

plt.subplot(2, 1, 2)
plt.plot(x2, y2, 'r.-')
plt.xlabel('time (s)')
plt.ylabel('Undamped')

plt.show()

## Histograms

In [194]:
"""
Demo of the histogram (hist) function with a few features.

In addition to the basic histogram, this demo shows a few optional features:

    * Setting the number of data bins
    * The ``normed`` flag, which normalizes bin heights so that the integral of
      the histogram is 1. The resulting histogram is a probability density.
    * Setting the face color of the bars
    * Setting the opacity (alpha value).

"""
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt


# example data
mu = 100  # mean of distribution
sigma = 15  # standard deviation of distribution
x = mu + sigma * np.random.randn(10000)

num_bins = 50
# the histogram of the data
n, bins, patches = plt.hist(x, num_bins, normed=1, facecolor='green', alpha=0.5)
# add a 'best fit' line
y = mlab.normpdf(bins, mu, sigma)
plt.plot(bins, y, 'r--')
plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title(r'Histogram of IQ: $\mu=100$, $\sigma=15$')

# Tweak spacing to prevent clipping of ylabel
plt.subplots_adjust(left=0.15)
plt.show()


In [195]:
n, bins, patches = plt.hist(
    x, 
    bins = 5, 
    normed=0,
    facecolor='red', 
    color = 'red',
    alpha=0.5, 
    cumulative = 0,
    histtype = 'stepfilled',
    # orientation = 'horizontal',
    orientation = 'vertical',
    log = 0)

## Path demo

In [225]:
"""
Demo of a PathPatch object.
"""
import matplotlib.path as mpath
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt


fig, ax = plt.subplots()

Path = mpath.Path
path_data = [
    (Path.MOVETO, (1.58, -2.57)),
    (Path.CURVE4, (0.35, -1.1)),
    (Path.CURVE4, (-1.75, 2.0)),
    (Path.CURVE4, (0.375, 2.0)),
    (Path.LINETO, (0.85, 1.15)),
    (Path.CURVE4, (2.2, 3.2)),
    (Path.CURVE4, (3, 0.05)),
    (Path.CURVE4, (2.0, -0.5)),
    (Path.CLOSEPOLY, (1.58, -2.57)),
    ]
codes, verts = zip(*path_data)
path = mpath.Path(verts, codes)
patch = mpatches.PathPatch(path, facecolor='r', alpha=0.5)
ax.add_patch(patch)

# plot control points and connecting lines
x, y = zip(*path.vertices)
line, = ax.plot(x, y, 'go-')

ax.grid(1)
ax.axis('equal')
plt.show()


## mplot3d

In [226]:
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
ax = fig.gca(projection='3d')
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)
surf = ax.plot_surface(X, Y, Z, rstride=1, cstride=1, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)
ax.set_zlim(-1.01, 1.01)

ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))

fig.colorbar(surf, shrink=0.5, aspect=5)

plt.show()

## Bar charts

In [260]:
"""
Bar chart demo with pairs of bars grouped for easy comparison.
"""
import numpy as np
import matplotlib.pyplot as plt


n_groups = 5

means_men = (20, 35, 30, 35, 27)
std_men = (2, 3, 4, 1, 2)

means_women = (25, 32, 34, 20, 25)
std_women = (3, 5, 2, 3, 3)

fig, ax = plt.subplots()

index = np.arange(n_groups)
bar_width = 0.35

opacity = 0.4
error_config = {'ecolor': '0.3'}

rects1 = plt.bar(index, means_men, bar_width,
                 alpha=opacity,
                 color='b',
                 yerr=std_men,
                 error_kw=error_config,
                 label='Men')

rects2 = plt.bar(index + bar_width, means_women, bar_width,
                 alpha=opacity,
                 color='r',
                 yerr=std_women,
                 error_kw=error_config,
                 label='Women')

plt.xlabel('Group')
plt.ylabel('Scores')
plt.title('Scores by group and gender')
plt.xticks(index + bar_width, ('A', 'B', 'C', 'D', 'E'))
plt.legend()

plt.tight_layout()
plt.show()


## Table demo

In [261]:
"""
Demo of table function to display a table within a plot.
"""
import numpy as np
import matplotlib.pyplot as plt


data = [[  66386,  174296,   75131,  577908,   32015],
        [  58230,  381139,   78045,   99308,  160454],
        [  89135,   80552,  152558,  497981,  603535],
        [  78415,   81858,  150656,  193263,   69638],
        [ 139361,  331509,  343164,  781380,   52269]]

columns = ('Freeze', 'Wind', 'Flood', 'Quake', 'Hail')
rows = ['%d year' % x for x in (100, 50, 20, 10, 5)]

values = np.arange(0, 2500, 500)
value_increment = 1000

# Get some pastel shades for the colors
colors = plt.cm.BuPu(np.linspace(0, 0.5, len(rows)))
n_rows = len(data)

index = np.arange(len(columns)) + 0.3
bar_width = 0.4

# Initialize the vertical-offset for the stacked bar chart.
y_offset = np.array([0.0] * len(columns))

# Plot bars and create text labels for the table
cell_text = []
for row in range(n_rows):
    plt.bar(index, data[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + data[row]
    cell_text.append(['%1.1f' % (x/1000.0) for x in y_offset])
# Reverse colors and text labels to display the last value at the top.
colors = colors[::-1]
cell_text.reverse()

# Add a table at the bottom of the axes
the_table = plt.table(cellText=cell_text,
                      rowLabels=rows,
                      rowColours=colors,
                      colLabels=columns,
                      loc='bottom')

# Adjust layout to make room for the table:
plt.subplots_adjust(left=0.2, bottom=0.2)

plt.ylabel("Loss in ${0}'s".format(value_increment))
plt.yticks(values * value_increment, ['%d' % val for val in values])
plt.xticks([])
plt.title('Loss by Disaster')

plt.show()


In [262]:
rows

['100 year', '50 year', '20 year', '10 year', '5 year']

In [263]:
values

array([   0,  500, 1000, 1500, 2000])

In [264]:
index

array([ 0.3,  1.3,  2.3,  3.3,  4.3])

In [266]:
data[0]

[66386, 174296, 75131, 577908, 32015]

In [267]:
colors = plt.cm.BuPu(np.linspace(0, 0.5, len(rows)))
colors

array([[ 0.96862745,  0.98823529,  0.99215686,  1.        ],
       [ 0.87792388,  0.92510573,  0.95664745,  1.        ],
       [ 0.74800463,  0.82674357,  0.9015917 ,  1.        ],
       [ 0.61877742,  0.73550175,  0.85397925,  1.        ],
       [ 0.54901963,  0.58559018,  0.77517879,  1.        ]])

In [269]:
colors[::-1]

array([[ 0.54901963,  0.58559018,  0.77517879,  1.        ],
       [ 0.61877742,  0.73550175,  0.85397925,  1.        ],
       [ 0.74800463,  0.82674357,  0.9015917 ,  1.        ],
       [ 0.87792388,  0.92510573,  0.95664745,  1.        ],
       [ 0.96862745,  0.98823529,  0.99215686,  1.        ]])

In [270]:
type(colors)

numpy.ndarray

In [272]:
xs = [[1, 2, 3],
      [4,5, 6],
      [7, 8, 9],
      [10, 11, 12]]

In [276]:
xs[:-1:-1]

[]

## Scatter demo

In [71]:
"""
Demo of scatter plot with varying marker colors and sizes.
"""
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cbook as cbook

# Load a numpy record array from yahoo csv data with fields date,
# open, close, volume, adj_close from the mpl-data/example directory.
# The record array stores python datetime.date as an object array in
# the date column
datafile = cbook.get_sample_data('goog.npy')
try:
    # Python3 cannot load python2 .npy files with datetime(object) arrays
    # unless the encoding is set to bytes. Hovever this option was
    # not added until numpy 1.10 so this example will only work with
    # python 2 or with numpy 1.10 and later
    price_data = np.load(datafile, encoding='bytes').view(np.recarray)
except TypeError:
    price_data = np.load(datafile).view(np.recarray)
price_data = price_data[-250:]  # get the most recent 250 trading days

delta1 = np.diff(price_data.adj_close)/price_data.adj_close[:-1]

# Marker size in units of points^2
volume = (15 * price_data.volume[:-2] / price_data.volume[0])**2
close = 0.003 * price_data.close[:-2] / 0.003 * price_data.open[:-2]

fig, ax = plt.subplots()
ax.scatter(delta1[:-1], delta1[1:], c=close, s=volume, alpha=0.5)

ax.set_xlabel(r'$\Delta_i$', fontsize=20)
ax.set_ylabel(r'$\Delta_{i+1}$', fontsize=20)
ax.set_title('Volume and percent change')

ax.grid(True)
fig.tight_layout()

plt.show()


in try part
<class 'numpy.recarray'>


In [40]:
type(datafile)

file

In [86]:
datafile = cb.get_sample_data('goog.npy')
price_data = np.load(datafile, encoding = 'bytes').view(np.recarray)
# price_data = np.load(datafile, encoding = 'bytes')
price_data = price_data[-10:]
price_data

rec.array([ (datetime.date(2008, 10, 1), 411.15, 416.98, 403.1, 411.72, 6234800, 411.72),
 (datetime.date(2008, 10, 2), 409.79, 409.98, 386.0, 390.49, 5984900, 390.49),
 (datetime.date(2008, 10, 3), 397.35, 412.5, 383.07, 386.91, 7992900, 386.91),
 (datetime.date(2008, 10, 6), 373.98, 375.99, 357.16, 371.21, 11220600, 371.21),
 (datetime.date(2008, 10, 7), 373.33, 374.98, 345.37, 346.01, 11054400, 346.01),
 (datetime.date(2008, 10, 8), 330.16, 358.99, 326.11, 338.11, 11826400, 338.11),
 (datetime.date(2008, 10, 9), 344.52, 348.57, 321.67, 328.98, 8075000, 328.98),
 (datetime.date(2008, 10, 10), 313.16, 341.89, 310.3, 332.0, 10597800, 332.0),
 (datetime.date(2008, 10, 13), 355.79, 381.95, 345.75, 381.02, 8905500, 381.02),
 (datetime.date(2008, 10, 14), 393.53, 394.5, 357.0, 362.71, 7784800, 362.71)], 
          dtype=[('date', 'O'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('volume', '<i8'), ('adj_close', '<f8')])

In [89]:
delta1 = np.diff(price_data.adj_close) / price_data.adj_close[:-1]
delta1

array([-0.05156417, -0.00916797, -0.04057791, -0.0678861 , -0.02283171,
       -0.02700305,  0.00917989,  0.1476506 , -0.04805522])

In [90]:
price_data.volume

array([ 6234800,  5984900,  7992900, 11220600, 11054400, 11826400,
        8075000, 10597800,  8905500,  7784800])

In [91]:
price_data.volume[:-2]

array([ 6234800,  5984900,  7992900, 11220600, 11054400, 11826400,
        8075000, 10597800])

In [92]:
price_data.volume[0]

6234800

In [96]:
volume = (15 * price_data.volume[:-2] / price_data.volume[0]) ** 2
volume

array([225, 196, 361, 676, 676, 784, 361, 625])

In [107]:
close = price_data.close[:-2] / (price_data.open[:-2])
close

array([ 1.00138636,  0.95290271,  0.97372593,  0.99259319,  0.92682078,
        1.02407923,  0.95489377,  1.06016094])

In [109]:
fig, ax = plt.subplots()
ax.scatter(delta1[:-1], delta1[1:], c = close, s = volume, alpha = 0.5)

ax.set_xlabel(r'$\Delta_i$', fontsize=20)
ax.set_ylabel(r'$\Delta_{i+1}$', fontsize=20)
ax.set_title('Volume and percent change')

In [110]:
fig, ax = plt.subplots()
ax.scatter(delta1[:-1], delta1[1:], c = close, s = volume, alpha = 0.5)

ax.set_xlabel(r'$\Delta_i$', fontsize=20)
ax.set_ylabel(r'$\Delta_{i+1}$', fontsize=20)
ax.set_title('Volume and percent change')

ax.grid(True)
fig.tight_layout()

plt.show()



In [111]:
plt.tight_layout?